version: '3.2'
services:
  prometheus:
    restart: always
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - redis
  redis:
    restart: always
    image: redis:alpine3.12
    container_name: redis
    ports:
    - 6379:6379 
  grafana:
    restart: always
    image: grafana/grafana:7.3.6
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
