{
 "title": "My Node Explorer dashboard",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": "label_values(origin_prometheus)"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
   },
   { "name": "node", "label": "Instance", "query": "label_values(instance)" },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{id=~\"/docker/.*\",instance=~\"$node\"}[10s]))"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 9 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\",instance=~\"$node\"}) by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",instance=~\"$node\"}-container_memory_usage_bytes{name!=\"\",instance=~\"$node\"})by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",instance=~\"$node\"}) by (name)"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "graph",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "HW Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp1\"}"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  }
 ]
}