version: "3"
services:
  compile:
    image: ${CI_REGISTRY_IMAGE_COMPILER}
    command: /bin/bash -c "chmod +x compile.sh && ./compile.sh"
    volumes:
      - ./project/:/stm32
      - ./build/:/build
