version: "3"
services:
  motion:
    image: ${CI_REGISTRY_IMAGE_MOTION}
    command: motion start -n
    ports: 
      - 8081:8081
    volumes:
      - ./motion/config/motion.conf:/etc/motion/motion.conf
      - ./motion/config/motion:/etc/default/motion
    devices:
      - /dev/video0:/dev/video0
    
  st-link:
    image: ${CI_REGISTRY_IMAGE_STLINK}
    command: /bin/bash -c "chmod +x flash.sh && ./flash.sh"
    volumes:
      - ./build:/build
      - ./project/flash.sh:/build/flash.sh
    devices:
      - /dev/bus/usb:/dev/bus/usb
